package e93.assembler;

import javax.annotation.Generated;

/**
 * @author markford
 */
public enum OpCode {
    // instructions
    ADD(0),
    SUB(1),
    NAND(2),
    SLT(3),
    SGT(4),
    SET(5),
    SLL(6),
    SRA(7),
    SRL(8),
    ORI(9),
    BOZ(10),
//    J(11),
    SW(12),
    LW(13),
    LUI(14);

    // pseudoinstructions
    // no opcodes for these pesudoinstructions
    // ADDI
    // SUBI


    private final int value;

    OpCode(int value) {
        this.value = value;
    }

    @Generated("generated by IDE")
    public int getValue() {
        return value;
    }

    public static OpCode fromEncoded(int value) {
        for(OpCode oc : values()) {
           if (oc.getValue() == value) {
               return oc;
           }
        }
        throw new IllegalArgumentException("unknown opcode:" + value);
    }
}
