all:
	mkdir -p bin
	javac -g -d 'bin/' src/main/java/WordCount.java

test1:
	java -cp bin WordCount test1.txt

test2:
	java -cp bin WordCount test2.txt

run:
	java -cp bin WordCount test1.txt

clean:
	rm -rf bin