# Generated by Django 2.2.7 on 2019-11-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedcoin',
            name='coinImage',
            field=models.CharField(default='wefw', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchedcoin',
            name='coinSymbol',
            field=models.CharField(default='wefwe', max_length=64),
            preserve_default=False,
        ),
    ]
