DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
       ID INT(11) NOT NULL AUTO_INCREMENT
     , CATEGORY VARCHAR(100) NOT NULL
     , ISBN VARCHAR(10) NOT NULL
     , TITLE VARCHAR(200) NOT NULL
     , PUBLISHER VARCHAR(100)
     , PRICE DECIMAL(4,2)
     , PRIMARY KEY (ID)
);