# Generated by Django 2.2.7 on 2019-11-09 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28)),
                ('childOf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='orders.MenuCategory')),
            ],
        ),
    ]
