# Generated by Django 2.2.7 on 2019-11-09 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191109_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='isChild',
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='childOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='orders.MenuCategory'),
        ),
    ]
