# Generated by Django 2.2.7 on 2019-11-09 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191109_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='childOf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='orders.MenuCategory'),
        ),
    ]
