# Generated by Django 2.2.7 on 2019-11-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191109_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='description',
            field=models.CharField(default=2, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menucategory',
            name='displayName',
            field=models.CharField(default=1, max_length=28),
            preserve_default=False,
        ),
    ]
