# Generated by Django 2.2.7 on 2019-11-10 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191109_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('maxCustomizations', models.IntegerField()),
                ('price', models.IntegerField()),
                ('menuCategory', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, related_name='menuItems', to='orders.MenuCategory')),
            ],
        ),
    ]
