# Generated by Django 2.2.7 on 2019-11-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191110_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='largePrice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='smallPrice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
