# Generated by Django 2.2.7 on 2019-11-10 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191110_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='largePrice',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='smallPrice',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='variationOf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, related_name='variations', to='orders.MenuItem'),
        ),
    ]
