# Generated by Django 2.2.7 on 2019-11-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20191110_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
