# Generated by Django 2.2.7 on 2019-11-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_menuitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], default='S', max_length=16),
        ),
    ]
