# Generated by Django 2.2.7 on 2019-11-10 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20191110_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large'), ('None', 'None')], default='S', max_length=16),
        ),
        migrations.CreateModel(
            name='MenuItemXVariations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variationName', models.CharField(max_length=64)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large'), ('None', 'None')], default='None', max_length=16)),
                ('priceWithVariation', models.FloatField()),
                ('variationOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, related_name='variaions', to='orders.MenuItemXVariations')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('menuCategory', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, related_name='menuItms', to='orders.MenuCategory')),
            ],
        ),
    ]
