# Generated by Django 2.2.7 on 2019-11-10 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20191110_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemxvariations',
            name='variationOf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.ProtectedError, related_name='variaions', to='orders.MenuItemX'),
            preserve_default=False,
        ),
    ]
