# Generated by Django 2.2.7 on 2019-11-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20191110_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemxvariations',
            name='variationOf',
        ),
        migrations.AddField(
            model_name='menuitemx',
            name='variations',
            field=models.ManyToManyField(to='orders.MenuItemXVariations'),
        ),
    ]
