# Generated by Django 2.2.7 on 2019-11-10 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20191110_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemx',
            name='variations',
        ),
        migrations.AddField(
            model_name='menuitemxvariations',
            name='variationOf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.ProtectedError, related_name='variations', to='orders.MenuItemX'),
        ),
    ]
