# Generated by Django 2.2.7 on 2019-11-13 04:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20191110_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitemxvariations',
            old_name='variationName',
            new_name='displayName',
        ),
        migrations.AddField(
            model_name='menuitemx',
            name='basePrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='menuitemxvariations',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuitemx',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuitemxvariations',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuitemxvariations',
            name='priceWithVariation',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name=0.0),
        ),
    ]
