# Generated by Django 2.2.7 on 2019-11-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20191116_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='supportedModifiers',
            field=models.ManyToManyField(related_name='supportedMenuItems', to='orders.MenuItemModifier'),
        ),
    ]
