# Generated by Django 2.2.7 on 2019-11-16 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0019_auto_20191116_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='maximumModifiersAllowed',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('totalPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('menuItemId', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='orders.MenuItem')),
                ('modifiers', models.ManyToManyField(related_name='modifiers', to='orders.MenuItemModifier')),
                ('ticketId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='orders.Ticket')),
            ],
        ),
    ]
