# Generated by Django 2.2.7 on 2019-11-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20191116_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='totalPrice',
            new_name='totalItemPrice',
        ),
    ]
