# Generated by Django 2.2.7 on 2019-11-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20191116_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='childOf',
        ),
    ]
