# Generated by Django 2.2.7 on 2019-11-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_remove_menucategory_childof'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='isSubmitted',
            field=models.BooleanField(default=False),
        ),
    ]
