# Generated by Django 2.2.7 on 2019-11-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20191117_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='submittedOn',
            field=models.DateField(null=True),
        ),
    ]
