# Generated by Django 2.2.7 on 2019-11-20 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20191119_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.ticket',),
        ),
    ]
