# Generated by Django 2.2.7 on 2019-11-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20191120_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='maximumModifiersAllowed',
            field=models.IntegerField(),
        ),
    ]
