# Generated by Django 2.2.7 on 2019-11-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20191120_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='menuitemmodifier',
            name='description',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='supportedModifiers',
            field=models.ManyToManyField(blank=True, related_name='supportedMenuItems', to='orders.MenuItemModifier'),
        ),
    ]
